version: 2.1
jobs:
  pr_check:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - run: pwd
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: aws --version
      - run: curl "https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip" -o "packer.zip"
      - run: ls 
      - run: pwd
      - run: unzip packer.zip 
      - run: sudo mv packer /usr/local/bin/ 
      - run: packer validate template.json
      - run: packer build template.json
      
workflows:
    pr_check_workflow:
      jobs:
        - pr_check:
            filters:
              branches:
                only:
                  - /^pull\/.*$/
